export const FETCH_INGREDIENTS_CONSTRUCTOR_REQUEST = 'FETCH_INGREDIENTS_REQUEST';
export const FETCH_INGREDIENTS_CONSTRUCTOR_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_CONSTRUCTOR_FAILURE = 'FETCH_INGREDIENTS_FAILURE';
